# Generated by Django 4.0.3 on 2022-07-12 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='delete_flag',
            field=models.IntegerField(default=0),
        ),
    ]
