# Generated by Django 4.0.3 on 2022-07-19 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsApp', '0002_alter_profile_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow',
            name='request_status',
            field=models.CharField(choices=[('1', 'unapproved'), ('2', 'approved')], default=1, max_length=2),
        ),
    ]
