# Generated by Django 4.0.3 on 2022-07-06 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsApp', '0002_issuedbook_studentextra'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='book_cover',
            field=models.ImageField(blank=True, upload_to='media/book-covers'),
        ),
    ]
