# Generated by Django 4.0.3 on 2022-07-19 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsApp', '0003_borrow_request_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='request_status',
            field=models.CharField(blank=True, choices=[('1', 'unapproved'), ('2', 'approved')], default=1, max_length=2, null=True),
        ),
    ]
