# Generated by Django 4.0.3 on 2022-07-09 18:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lmsApp', '0003_books_book_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_id_fk', to=settings.AUTH_USER_MODEL),
        ),
    ]
