# Generated by Django 4.0.3 on 2022-08-07 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsApp', '0004_alter_borrow_request_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.FileField(blank=True, default='default/avatar.png', null=True, upload_to='avatars/'),
        ),
    ]
