# Generated by Django 4.0.3 on 2022-08-21 10:18

from django.db import migrations, models
import lmsApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsApp', '0005_alter_profile_avatar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IssuedBook',
        ),
        migrations.AlterField(
            model_name='borrow',
            name='return_date',
            field=models.DateField(default=lmsApp.models.get_expiry),
        ),
    ]
