# Generated by Django 4.0.3 on 2022-07-01 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='course',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
